
export interface Obra {
  id: number;
  titulo: string;
  imagenurl: string; 
  slug: string;
  imagen: string;
  descripcion: string[] ;
  categoria: string;
  anio: string;
  ubicacion: string;
  superficie: string; // Opcional, si no se especifica
  imagenes?: string[];}

export const obrasResidenciales: Obra[] = [
  {
    id: 1,
    titulo: 'Ozanam 446',
    imagenurl: 'ozanam',
    slug: 'ozanam-446',
    imagen: '/ozanam.jpg',
descripcion: [
  "En esta vivienda se llevó a cabo la refuncionalización del quincho, que fue transformado en comedor e integrado a una cocina completamente renovada.",
  "Se rediseñó el lavadero y se reorganizaron las instalaciones, vinculando ambos espacios mediante una barra desayunadora.",
  "También se realizaron mejoras en habitaciones y baños: se repararon muros, se pintó con látex y se rediseñó la zona húmeda para incorporar un baño principal y un toilette de uso público, con nuevas instalaciones sanitarias y una bomba presurizadora.",
  "En la planta alta se construyó una nueva habitación con muros dobles, barrera hidrófuga y losa alivianada con perlas de telgopor.",
  "Al fondo del lote, se sumó un espacio de guardado o taller con las mismas técnicas constructivas."
],
    categoria: 'Residenciales',
    anio: '2022',
    ubicacion: 'Morón, Buenos Aires',
    superficie: '150 m²',
    imagenes: [
      "/Obras/residencial/ozanam/ozanam1.webp",
      "/Obras/residencial/ozanam/ozanam2.webp",
      "/Obras/residencial/ozanam/ozanam3.webp",
      "/Obras/residencial/ozanam/ozanam4.webp",
      "/Obras/residencial/ozanam/ozanam5.webp",
      "/Obras/residencial/ozanam/ozanam6.webp",
      "/Obras/residencial/ozanam/ozanam7.webp",
      "/Obras/residencial/ozanam/ozanam8.webp",
      "/Obras/residencial/ozanam/ozanam9.webp",
      "/Obras/residencial/ozanam/ozanam10.webp",
      "/Obras/residencial/ozanam/ozanam11.webp",
      "/Obras/residencial/ozanam/ozanam12.webp",
      "/Obras/residencial/ozanam/ozanam13.webp",
      "/Obras/residencial/ozanam/ozanam14.webp",
      "/Obras/residencial/ozanam/ozanam15.webp",
      "/Obras/residencial/ozanam/ozanam16.webp",
      "/Obras/residencial/ozanam/ozanam17.webp",
      "/Obras/residencial/ozanam/ozanam18.webp",
      "/Obras/residencial/ozanam/ozanam19.webp",

    ]
  },
  {
    id: 2,
    titulo: 'Ate. Brown 670',
    imagenurl: 'ate-brown',
    slug: 'ate-brown-670',
    imagen: '/Obras/residencial/ate-brown/ate-brown1.webp',
    descripcion:[ "Esta vivienda de tres plantas presentaba un grave problema de humedad en el subsuelo (nivel -1), especialmente en los muros lindantes con el terreno y en la base de los cimientos. Además, se detectó una pérdida proveniente de un caño roto del toilette en el nivel 0, lo que agravaba la situación.",
"Para resolverlo, se procedió a descubrir por completo los muros afectados y se aplicó una capa hidrófuga utilizando Sika Monotop 107, junto con una barrera horizontal con Ceresita. Una vez finalizada la impermeabilización, los muros fueron rebozados nuevamente, dejándolos listos para ser pintados.","Por otro lado, los tramos de cañerías deterioradas, originalmente de fibrocemento, fueron reemplazados por una solución moderna, asegurando una mayor durabilidad y eficiencia."],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/ate-brown/ate-brown1.webp",
      "/Obras/residencial/ate-brown/ate-brown2.webp",
      "/Obras/residencial/ate-brown/ate-brown3.webp",
      "/Obras/residencial/ate-brown/ate-brown4.webp",
      "/Obras/residencial/ate-brown/ate-brown5.webp",
      "/Obras/residencial/ate-brown/ate-brown6.webp",
      "/Obras/residencial/ate-brown/ate-brown7.webp",
      "/Obras/residencial/ate-brown/ate-brown8.webp",
      "/Obras/residencial/ate-brown/ate-brown9.webp",
      "/Obras/residencial/ate-brown/ate-brown10.webp",
      "/Obras/residencial/ate-brown/ate-brown11.webp",
      "/Obras/residencial/ate-brown/ate-brown12.webp",
      "/Obras/residencial/ate-brown/ate-brown13.webp",
      "/Obras/residencial/ate-brown/ate-brown14.webp",
    ]
  },
  {
    id: 3,
    titulo: 'Glenmore',
    imagenurl: 'glenmore-pilar',
    slug: 'glenmore',
    imagen: '/Obras/residencial/glenmore-pilar/glenmore-pilar1.webp',
    descripcion: [],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: 'Pilar, Buenos Aires',
    superficie: '',
    imagenes: [
      "/Obras/residencial/glenmore-pilar/glenmore-pilar1.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar2.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar3.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar4.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar5.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar6.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar7.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar8.webp",
      "/Obras/residencial/glenmore-pilar/glenmore-pilar9.webp",
    ]
  },
{
    id: 4,
    titulo: 'Local Comercial Nordelta',
    imagenurl: 'nordelta',
    slug: 'nordelta',
    imagen: '/Obras/residencial/nordelta/nordelta1.webp',
    descripcion: [],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: 'Nordelta, Buenos Aires',
    superficie: '',
    imagenes: [
      "/Obras/residencial/nordelta/nordelta1.webp",
      "/Obras/residencial/nordelta/nordelta2.webp",
      "/Obras/residencial/nordelta/nordelta3.webp",
      "/Obras/residencial/nordelta/nordelta4.webp",
      "/Obras/residencial/nordelta/nordelta5.webp",
      "/Obras/residencial/nordelta/nordelta6.webp",
      "/Obras/residencial/nordelta/nordelta7.webp",
      "/Obras/residencial/nordelta/nordelta8.webp",
      "/Obras/residencial/nordelta/nordelta9.webp",
      "/Obras/residencial/nordelta/nordelta10.webp",
      "/Obras/residencial/nordelta/nordelta11.webp",
    ]
  },
  {
    id: 5,
    titulo: 'Piedras',
    imagenurl: 'piedras',
    slug: 'piedras',
    imagen: '/Obras/residencial/piedras/piedras1.webp',
descripcion: [
  "Intervención sobre la cocina de una propiedad ubicada en un edificio histórico de la calle Piedras, en pleno microcentro porteño.",
  "Aunque la vivienda se encontraba en excelente estado de conservación, la cocina presentaba un notable deterioro y una distribución poco funcional.",
  "Los propietarios, una familia tipo, necesitaban optimizar el espacio disponible, priorizando la cocina como núcleo de la vida diaria.",
  "El proyecto propuso reubicar la bacha y el artefacto de cocina, integrándolos en una mesada continua con barra desayunadora.",
  "Se incorporó además un espacio destinado a comedor diario con mesa y sillas, mejorando la circulación y el uso general.",
  "La barra no solo articula visualmente el ambiente, sino que ordena el espacio, resolviendo problemas de escala que no se solucionaban con propuestas previas."
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/piedras/piedras1.webp",
      "/Obras/residencial/piedras/piedras2.webp",
      "/Obras/residencial/piedras/piedras3.webp",
      "/Obras/residencial/piedras/piedras4.webp",
      "/Obras/residencial/piedras/piedras5.webp",
      "/Obras/residencial/piedras/piedras6.webp",
      "/Obras/residencial/piedras/piedras7.webp",
      "/Obras/residencial/piedras/piedras8.webp",
      "/Obras/residencial/piedras/piedras9.webp",
      "/Obras/residencial/piedras/piedras10.webp",
      "/Obras/residencial/piedras/piedras11.webp",
    ]
  },
  {
    id: 6,
    titulo: 'Medrano 332',
    imagenurl: 'medrano',
    slug: 'medrano-332',
    imagen: '/Obras/residencial/medrano/medrano1.webp',
descripcion: [],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: 'CABA, Buenos Aires',
    superficie: '',
    imagenes: [
      "/Obras/residencial/medrano/medrano1.webp",
      "/Obras/residencial/medrano/medrano2.webp",
      "/Obras/residencial/medrano/medrano3.webp",
      "/Obras/residencial/medrano/medrano4.webp",
      "/Obras/residencial/medrano/medrano5.webp",
      "/Obras/residencial/medrano/medrano6.webp",
      "/Obras/residencial/medrano/medrano7.webp",
      "/Obras/residencial/medrano/medrano8.webp",
      "/Obras/residenciales/medrano/medrano9.webp",
      "/Obras/residenciales/medrano/medrano10.webp",
    ]
  },  
  {
    id: 7,
    titulo: 'Martinez',
    imagenurl: 'martinez',
    slug: 'martinez',
    imagen: '/Obras/residencial/martinez/martinez1.webp',
  descripcion: [
  "Chalet típico de la zona, sobre el cual se realizó una remodelación completa de cocina y baños, incluyendo instalaciones y revestimientos de pisos y paredes.",
  "Se reinstalaron equipos de aire acondicionado y se modificaron antiguas ubicaciones de artefactos de calefacción para mejorar su eficiencia.",
  "Se llevó a cabo un trabajo de pintura integral en toda la vivienda y se pusieron en funcionamiento equipos de hidromasaje que estaban en desuso.",
  "La casa había estado deshabitada durante un largo tiempo, por lo que el proyecto consistió en una puesta en valor total que permitió reincorporarla al mercado inmobiliario."
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/martinez/martinez1.webp",
      "/Obras/residencial/martinez/martinez2.webp",
      "/Obras/residencial/martinez/martinez3.webp",
      "/Obras/residencial/martinez/martinez4.webp",
      "/Obras/residencial/martinez/martinez5.webp",
      "/Obras/residencial/martinez/martinez6.webp",
      "/Obras/residencial/martinez/martinez7.webp",
      "/Obras/residencial/martinez/martinez8.webp",
      "/Obras/residenciales/martinez/martinez9.webp",
      "/Obras/residenciales/martinez/martinez10.webp",
    ]
  },
{
    id: 8,
    titulo: 'Lavalle 3644',
    imagenurl: 'lavalle',
    slug: 'lavalle-3644',
    imagen: '/Obras/residencial/lavalle/lavalle1.webp',
  descripcion: [
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: 'CABA, Buenos Aires',
    superficie: '',
    imagenes: [
      "/Obras/residencial/lavalle/lavalle1.webp",
      "/Obras/residencial/lavalle/lavalle2.webp",
      "/Obras/residencial/lavalle/lavalle3.webp",
      "/Obras/residencial/lavalle/lavalle4.webp",
      "/Obras/residencial/lavalle/lavalle5.webp",
      "/Obras/residencial/lavalle/lavalle6.webp",
      "/Obras/residencial/lavalle/lavalle7.webp",
      "/Obras/residencial/lavalle/lavalle8.webp",
      "/Obras/residenciales/lavalle/lavalle9.webp",
      "/Obras/residenciales/lavalle/lavalle10.webp",
    ]
  },
{
    id: 9,
    titulo: 'Julio A. Roca 620',
    imagenurl: 'julio-roca',
    slug: 'julio-a-roca-620',
    imagen: '/Obras/residencial/julio-roca/julio-roca1.webp',
  descripcion: [
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/julio-roca/julio-roca1.webp",
      "/Obras/residencial/julio-roca/julio-roca2.webp",
      "/Obras/residencial/julio-roca/julio-roca3.webp",
      "/Obras/residencial/julio-roca/julio-roca4.webp",
      "/Obras/residencial/julio-roca/julio-roca5.webp",
      "/Obras/residencial/julio-roca/julio-roca6.webp",
      "/Obras/residencial/julio-roca/julio-roca7.webp",
      "/Obras/residencial/julio-roca/julio-roca8.webp",
      "/Obras/residenciales/julio-roca/julio-roca9.webp",
      "/Obras/residenciales/julio-roca/julio-roca10.webp",
    ]
  },
   {
    id: 10,
    titulo: 'Las Araucarias 1536',
    imagenurl: 'las-araucarias',
    slug: 'las-araucarias-1536',
    imagen: '/Obras/residencial/las-araucarias/las-araucarias1.webp',
    descripcion: [
  "Proyecto de reforma integral en un PH típico por pasillo, con más de 100 años de antigüedad.",
  "El objetivo fue refuncionalizar completamente el espacio, conservando la esencia original de la propiedad.",
  "Se propuso un nuevo esquema estructural utilizando elementos metálicos, permitiendo la creación de un segundo piso destinado a los espacios más privados y principales.",
  "También se renovaron las instalaciones eléctricas, sanitarias y cloacales, y se reemplazaron los revestimientos.",
  "Aquellos elementos con valor patrimonial fueron restaurados y puestos en valor según lo definido en el proyecto."
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/las-araucarias/las-araucarias1.webp",
    ]
  },
  {
    id: 11,
    titulo: 'Proyecto Inmobiliario',
    imagenurl: 'proyecto-inmobiliario',
    slug: 'proyecto-inmobiliario',
    imagen: '/Obras/residencial/proyecto-inmobiliario/proyecto-inmobiliario1.webp',
   descripcion: [
  "Proyecto inmobiliario en etapa de desarrollo, en búsqueda de inversores interesados en participar.",
  "La propuesta consiste en la construcción de un edificio de 5 pisos, con 4 departamentos por nivel y la posibilidad de incorporar cocheras.",
  "Actualmente se están llevando a cabo estudios de mercado y análisis de zonificación para definir la viabilidad y alcance del proyecto."
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/proyecto-inmobiliario/proyecto-inmobiliario1.webp",
      "/Obras/residencial/proyecto-inmobiliario/proyecto-inmobiliario2.webp",
      "/Obras/residencial/proyecto-inmobiliario/proyecto-inmobiliario3.webp",
      "/Obras/residencial/proyecto-inmobiliario/proyecto-inmobiliario4.webp",
      "/Obras/residencial/proyecto-inmobiliario/proyecto-inmobiliario5.webp",
      "/Obras/residencial/proyecto-inmobiliario/proyecto-inmobiliario6.webp",
    ]
  },
  {
    id: 12,
    titulo: 'Pola 975',
    imagenurl: 'pola',
    slug: 'pola-975',
    imagen: '/Obras/residencial/pola/pola1.webp',
   descripcion: [
  "En este PH ubicado en Villa Luro se realizó un trabajo de impermeabilización integral, tanto en muros como en solados.",
  "El principal problema era la humedad ascendente, que impedía aplicar cualquier tipo de revestimiento.",
  "Se demolió el piso y se descubrieron los muros hasta el ladrillo, aplicando las capas de impermeabilización necesarias para detener la propagación de la humedad.",
  "Los muros fueron seccionados parcialmente por etapas en su parte inferior, permitiendo la construcción de un cajón hidrófugo.",
  "El piso fue demolido hasta llegar a la tosca, que se compactó para luego construir un nuevo contrapiso con capa hidrófuga y un alisado de cemento, dejándolo listo para la colocación de un piso flotante."
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: 'Villa Luro, Buenos Aires',
    superficie: '',
    imagenes: [
      "/Obras/residencial/pola/pola1.webp",
      "/Obras/residencial/pola/pola2.webp",
      "/Obras/residencial/pola/pola3.webp",
      "/Obras/residencial/pola/pola4.webp",
      "/Obras/residencial/pola/pola5.webp",
      "/Obras/residencial/pola/pola6.webp",
      "/Obras/residencial/pola/pola7.webp",
      "/Obras/residencial/pola/pola8.webp",
      "/Obras/residencial/pola/pola9.webp",
      "/Obras/residencial/pola/pola10.webp",
    ]
  },
    {
    id: 13,
    titulo: 'Juan B. Justo',
    imagenurl: 'juanbjusto',
    slug: 'juan-b-justo',
    imagen: '/Obras/residencial/juanbjusto/juanbjusto1.webp',
   descripcion: [
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/juanbjusto/juanbjusto1.webp",
      "/Obras/residencial/juanbjusto/juanbjusto2.webp",
      "/Obras/residencial/juanbjusto/juanbjusto3.webp",
      "/Obras/residencial/juanbjusto/juanbjusto4.webp",
      "/Obras/residencial/juanbjusto/juanbjusto5.webp",
      "/Obras/residencial/juanbjusto/juanbjusto6.webp",
      "/Obras/residencial/juanbjusto/juanbjusto7.webp",
      "/Obras/residencial/juanbjusto/juanbjusto8.webp",
      "/Obras/residencial/juanbjusto/juanbjusto9.webp",
      "/Obras/residencial/juanbjusto/juanbjusto10.webp",
      "/Obras/residencial/juanbjusto/juanbjusto11.webp",
    ]
  },
  {
    id: 14,
    titulo: 'Humberto Primo',
    imagenurl: 'humberto-primo',
    slug: 'humberto-primo',
    imagen: '/Obras/residencial/humberto-primo/humberto-primo1.webp',
   descripcion: [
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/humberto-primo/humberto-primo1.webp",
      "/Obras/residencial/humberto-primo/humberto-primo2.webp",
      "/Obras/residencial/humberto-primo/humberto-primo3.webp",
      "/Obras/residencial/humberto-primo/humberto-primo4.webp",
    ]
  },
      {
    id: 15,
    titulo: 'Golfers Pilar',
    imagenurl: 'golfers-pilar',
    slug: 'golfers-pilar',
    imagen: '/Obras/residencial/golfers-pilar/golfers-pilar1.webp',
   descripcion: [
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: 'Pilar, Buenos Aires',
    superficie: '',
    imagenes: [
      "/Obras/residencial/golfers-pilar/golfers-pilar1.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar2.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar3.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar4.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar5.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar6.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar7.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar8.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar9.webp",
      "/Obras/residencial/golfers-pilar/golfers-pilar10.webp",
    ]
  },
    {
    id: 16,
    titulo: 'Matheu 2134',
    imagenurl: 'matheu',
    slug: 'matheu-2134',
    imagen: '/Obras/residencial/matheu/matheu1.webp',
   descripcion: [
],
    categoria: 'Residenciales',
    anio: '',
    ubicacion: '',
    superficie: '',
    imagenes: [
      "/Obras/residencial/matheu/matheu1.webp",
      "/Obras/residencial/matheu/matheu2.webp",
      "/Obras/residencial/matheu/matheu3.webp",
    ]
  },



];

export const obrasIndustriales: Obra[] = [
 {
  id: 1,
  titulo: 'Playones de Hormigón - Pampa Energía',
  imagenurl: 'playones-hormigon',
  slug: 'playones-de-hormigon-pampa-energia',
  imagen: '/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon1.webp',
  descripcion: [
  ],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon1.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon2.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon3.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon4.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon5.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon6.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon7.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon8.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon9.webp",
    "/Obras/industrial/pampa-energia/playones-hormigon/playones-hormigon10.webp",
  ]
 },
  {
  id: 2,
  titulo: 'Cubiertas de Estacionamiento - Pampa Energía',
  imagenurl: 'cubierta-estacionamiento',
  slug: 'cubiertas-de-estacionamiento-pampa-energia',
  imagen: '/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento1.webp',
  descripcion: [
  "La obra consistió en fabricar, desarrollar y montar una nueva cubierta para el estacionamiento de empleados dentro de una planta industrial.",
  "La estructura existente fue reacondicionada y puesta en valor, y la cubierta fue diseñada cuidadosamente para no afectar el entorno inmediato, incluyendo árboles y canteros.",
  "Se diseñó y fabricó una zinguería a medida para el cierre y desagüe pluvial, incluyendo un soporte especial para fijar correas abulonadas, desarrollado mediante pantógrafo.",
  "Toda la estructura fue pintada con pintura epoxi para garantizar su durabilidad.",
  "Como complemento, se fabricó y montó un portón de dos hojas galvanizado, desarrollado en taller y adaptado a un cierre perimetral de cerco olímpico.",
  "Las hojas del portón fueron sujetadas con bisagras soldadas sobre postes de caño estructural de 3'', anclados a fundaciones tipo pilote con hormigón elaborado H21."
],
 categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento1.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento2.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento3.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento4.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento5.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento6.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento7.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento8.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento9.webp",
    "/Obras/industrial/pampa-energia/cubierta-estacionamiento/cubierta-estacionamiento10.webp",
  ]
 },
   {
  id: 3,
  titulo: 'Jaula de Almacenamiento - Pampa Energía',
  imagenurl: 'jaula-almacenamiento',
  slug: 'jaula-almacenamiento-pampa-energia',
  imagen: '/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento1.webp',
  descripcion: [
  "Para esta obra se construyó un muro cortafuego de hormigón armado de 20 cm de espesor, con malla sima Q524.",
  "Posteriormente, se fabricó y montó en obra una estructura metálica desarrollada en nuestro taller.",
  "La construcción está destinada al almacenamiento de tubos de gases, por lo que se diseñaron distintos sectores según tipo de uso.",
  "El espacio cuenta con puertas específicas y encausadores para una mejor organización y seguridad.",
  "La estructura metálica fue realizada con tubos estructurales de distintas secciones, definidos según memoria de cálculo, y fijada mediante abrocado a una platea de hormigón.",
  "La cubierta fue realizada en chapa T101, generando un cierre seguro y funcional al contenedor."
],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento1.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento2.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento3.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento4.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento5.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento6.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento7.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento8.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento9.webp",
    "/Obras/industrial/pampa-energia/jaula-almacenamiento/jaula-almacenamiento10.webp",
  ]
 },
  {
  id: 4,
  titulo: 'Veredas I - Pampa Energía',
  imagenurl: 'veredas1',
  slug: 'veredas1-pampa-energia',
  imagen: '/Obras/industrial/pampa-energia/veredas1/veredas11.webp',
  descripcion: [
  "En este sector se proyectaron nuevas veredas perimetrales, recuperando una zona que se encontraba en desuso.",
  "Las veredas existentes estaban completamente deterioradas, con tramos rotos, inexistentes o cubiertos por maleza.",
  "Se desmontó todo el sector, se enmarcó con moldes y se compactó el terreno vegetal como preparación.",
  "Luego se tomaron los niveles y se vertió la mezcla con piedra 6/20 para la base.",
  "A pedido del cliente, se aplicó una terminación con ferrite bermellón, generando una superficie estética y uniforme.",
  "Se incorporaron barreras hidrófugas mediante nylon de 200 micrones y se utilizó malla sima Q188 como armadura.",
  "La terminación final se realizó con el tradicional cepillado, garantizando durabilidad y buen acabado."
],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/pampa-energia/veredas1/veredas11.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas12.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas13.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas14.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas15.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas16.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas17.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas18.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas19.webp",
    "/Obras/industrial/pampa-energia/veredas1/veredas110.webp",
  ]
 },
 {
  id: 5,
  titulo: 'Veredas II - Pampa Energía',
  imagenurl: 'veredas2',
  slug: 'veredas2-pampa-energia',
  imagen: '/Obras/industrial/pampa-energia/veredas2/veredas21.webp',
  descripcion: [
  "Se proyectaron veredas para generar un circuito peatonal que conecte los diferentes accesos a la planta.",
  "La zona presentaba una alta circulación sin pasos peatonales definidos, lo que obligaba a transitar de forma riesgosa sobre la calzada vehicular.",
  "El recorrido fue trazado en conjunto con el estudio y los usuarios, priorizando seguridad y funcionalidad.",
  "Se retiraron las piedras partidas existentes y se colocaron moldes con sus correspondientes niveles.",
  "Luego se compactó el terreno suelo-tosca, se instaló una barrera antihumedad con nylon de 200 micrones y se colocaron mallas sima Q188.",
  "La vereda fue materializada con hormigón elaborado H21, con terminación en cepillado tradicional y bordes alisados."
],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/pampa-energia/veredas2/veredas21.webp",
   "/Obras/industrial/pampa-energia/veredas2/veredas22.webp",
   "/Obras/industrial/pampa-energia/veredas2/veredas23.webp",
   "/Obras/industrial/pampa-energia/veredas2/veredas24.webp",
   "/Obras/industrial/pampa-energia/veredas2/veredas25.webp",
   "/Obras/industrial/pampa-energia/veredas2/veredas26.webp",
   "/Obras/industrial/pampa-energia/veredas2/veredas27.webp",
   "/Obras/industrial/pampa-energia/veredas2/veredas28.webp",
  ]
 },
{
  id: 6,
  titulo: 'Arquetas de Hormigón - Pampa Energía',
  imagenurl: 'arquetas-hormigon',
  slug: 'arquetas-hormigon-pampa-energia',
  imagen: '/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon1.webp',
descripcion: [
  "Se realizó un tendido de 10 km para la instalación de cámaras de hormigón premoldeadas, destinadas a la red de comunicación de una planta industrial.",
  "Cada cámara fue equipada con su correspondiente tapa fabricada en chapa semilla melón, diseñada en nuestro taller.",
  "Además, se instaló un sistema de cañería tipo tritubo que vincula todas las cámaras entre sí.",
  "El objetivo de esta obra es garantizar la infraestructura necesaria para la conexión de fibra óptica entre las oficinas del complejo industrial."
],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon1.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon2.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon3.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon4.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon5.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon6.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon7.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon8.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon9.webp",
   "/Obras/industrial/pampa-energia/arquetas-hormigon/arquetas-hormigon10.webp",
  ]
 },
{
  id: 7,
  titulo: 'Cámaras de Vigilancia - Pampa Energía',
  imagenurl: 'camaras-de-vigilancia',
  slug: 'camaras-de-vigilancia-pampa-energia',
  imagen: '/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia1.webp',
descripcion: [
  "Obra de gran escala orientada a la instalación de un sistema de cámaras de vigilancia perimetral, desarrollada con un equipo de 15 operarios, maquinaria pesada, dirección de obra y supervisión de seguridad e higiene.",
  "Se ejecutó un tendido de 2500 metros de caño tritubo, alojado mediante zanjeo con retroexcavadora, alrededor del perímetro de la planta.",
  "Se colocaron cámaras de inspección de hormigón premoldeado, con tapas de hierro fabricadas en nuestro taller, y se montaron 35 cámaras de seguridad junto con sus respectivos postes galvanizados de hierro de 4'' de diámetro y 6 metros de altura.",
  "Los postes fueron anclados a fundaciones tipo pilote con hormigón elaborado H21, garantizando firmeza y durabilidad.",
  "La instalación incluyó una red eléctrica subterránea, tableros seccionales en chapa IP65 y conexiones mediante caños Daisa, con verificación y certificación oficial de puestas a tierra.",
  "En situaciones donde hubo que atravesar zonas de hormigón existente, se utilizaron equipos industriales de demolición para continuar con el tendido.",
  "Dentro de las cámaras, los cables fueron empalmados con uniones selladas con resina epoxi, asegurando protección y durabilidad a largo plazo.",
  "La obra se completó en dos meses y medio, contando con obrador, baños químicos y una planificación integral en cada etapa del proceso."
],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia1.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia2.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia3.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia4.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia5.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia6.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia7.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia8.webp",
   "/Obras/industrial/pampa-energia/camaras-de-vigilancia/camaras-de-vigilancia9.webp",
  ]
 },
 {
  id: 8,
  titulo: 'Vestuarios - Stellantis',
  imagenurl: 'stellantis',
  slug: 'vestuarios-stellantis',
  imagen: '/Obras/industrial/stellantis/vestuarios/stellantis1.webp',
descripcion: [
],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/stellantis/vestuarios/stellantis1.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis2.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis3.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis4.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis5.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis6.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis7.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis8.webp",
   "/Obras/industrial/stellantis/vestuarios/stellantis9.webp",
  ]
 },
  {
  id: 9,
  titulo: 'Giribone 927 - Fundacion SI',
  imagenurl: 'giribone',
  slug: 'giribone-927-fundacion-si',
  imagen: '/Obras/industrial/fundacionsi/giribone/giribone1.webp',
descripcion: [
  "En este depósito de 400 m² se realizó la demolición total del piso existente, que se encontraba en pésimo estado.",
  "Durante el trabajo se descubrió un segundo piso enterrado, el cual también fue retirado para comenzar desde nivel de base.",
  "Se perfiló el terreno y se aportó tosca en las zonas más desfavorables, garantizando una base firme y uniforme.",
  "Luego se tomaron los niveles, se colocaron tapas de inspección, barrera de humedad en nylon de 200 micrones y mallas sima Q188.",
  "La superficie se completó con el vertido de 60 m³ de hormigón elaborado H21, nivelado con allanadoras mecánicas y cuarzo marca Sika.",
  "Finalmente, se aplicó una laca protectora para preservar la terminación final del nuevo piso."
],
  categoria: 'Industriales',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/industrial/fundacionsi/giribone/giribone1.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone2.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone3.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone4.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone5.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone6.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone7.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone8.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone9.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone10.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone11.webp",
   "/Obras/industrial/fundacionsi/giribone/giribone12.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone13.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone14.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone15.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone16.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone17.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone18.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone19.webp",
    "/Obras/industrial/fundacionsi/giribone/giribone20.webp",
    
  ]
 },

];

export const obrasModulares: Obra[] = [
 {
  id: 1,
  titulo: 'Vivienda Modular - Una Planta',
  imagenurl: 'modulos1',
  slug: 'vivienda-modular-una-planta',
  imagen: '/Obras/modular/modulos1/modulos11.webp',
  descripcion: [
  "Sistema constructivo modular, desarrollado 100% en fábrica, listo para ser transportado e instalado en el lugar de destino.",
  "Las viviendas se entregan completamente terminadas, con instalaciones eléctricas, sanitarias, revestimientos, pintura, carpinterías, mobiliario y artefactos instalados.",
  "El sistema está basado en estructura metálica de alta prestación, cerramientos en seco, y permite múltiples terminaciones exteriores: chapas nórdicas, siding, placas cementicias o revoques plásticos combinados con madera.",
  "Es una solución ecoeficiente, sustentable y antisísmica, con posibilidad de incluir paneles solares y sistemas de recolección de agua de lluvia.",
  "Los módulos van de 42 m² a 80 m² y pueden personalizarse a medida del cliente con diseño tailor made."
],
  categoria: 'Modulares',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/modular/modulos1/modulos11.webp",
    "/Obras/modular/modulos1/modulos12.webp",
    "/Obras/modular/modulos1/modulos13.webp",
    "/Obras/modular/modulos1/modulos14.webp",
    "/Obras/modular/modulos1/modulos15.webp",
    "/Obras/modular/modulos1/modulos16.webp",
    "/Obras/modular/modulos1/modulos17.webp",
    "/Obras/modular/modulos1/modulos18.webp",
    "/Obras/modular/modulos1/modulos19.webp",

  ]
 },
  {
  id: 1,
  titulo: 'Vivienda Modular - Dos Plantas',
  imagenurl: 'modulos2',
  slug: 'vivienda-modular-dos-plantas',
  imagen: '/Obras/modular/modulos2/modulos21.webp',
  descripcion: [
  "La construcción modular de Diadema se realiza completamente bajo techo en fábrica, lo que garantiza calidad, precisión y cero desperdicio en obra.",
  "El sistema en seco permite rapidez en los tiempos de ejecución, alto control de calidad, y visitas programadas a planta durante el proceso.",
  "Se incluyen planos de arquitectura, documentación técnica completa, renders, instalaciones, mobiliario, y dirección de obra.",
  "La construcción llave en mano contempla desde movimiento de suelos hasta la instalación final de artefactos y mobiliario."
],
  categoria: 'Modulares',
  anio: '',
  ubicacion: '',
  superficie: '',
  imagenes: [
   "/Obras/modular/modulos2/modulos21.webp",
    "/Obras/modular/modulos2/modulos22.webp",
    "/Obras/modular/modulos2/modulos23.webp",
    "/Obras/modular/modulos2/modulos24.webp",
    "/Obras/modular/modulos2/modulos25.webp",
    "/Obras/modular/modulos2/modulos26.webp",
    "/Obras/modular/modulos2/modulos27.webp",
    "/Obras/modular/modulos2/modulos28.webp",
    "/Obras/modular/modulos2/modulos29.webp",
    "/Obras/modular/modulos2/modulos210.webp",
    "/Obras/modular/modulos2/modulos211.webp",

  ]
 },
];